version: 2
jobs:
  json-mapper:
    machine: true
    steps:
      - checkout
      - run: docker build -t jongo-extras-ci /home/circleci/project
      - run: mvn clean verify -f json-mapper

  json-query:
      machine: true
      steps:
        - checkout
        - run: docker build -t jongo-extras-ci /home/circleci/project
        - run: mvn clean verify -f json-query

  osgi:
      machine: true
      steps:
        - checkout
        - run: docker build -t jongo-extras-ci /home/circleci/project
        - run: mvn clean verify -f osgi

  release-validator:
      machine: true
      steps:
        - checkout
        - run: docker build -t jongo-extras-ci /home/circleci/project
        - run: mvn clean verify -f release-validator

  javax-persistence:
        machine: true
        steps:
          - checkout
          - run: docker build -t jongo-extras-ci /home/circleci/project
          - run: mvn clean verify -f javax-persistence

workflows:
  version: 2
  build_and_test:
    jobs:
      - json-mapper
      - json-query
      - osgi
      - release-validator
      - javax-persistence